deliverable 2/Controllers/ComputerActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using deliverable_2.Models;

namespace deliverable_2.Controllers
{
    public class ComputerActivityController : Controller
    {
        // GET: ComputerActivity
        EducationEntities db = new EducationEntities();
        public ActionResult ComputerActivity()
        {
            List<ActivityQuestion> ActivityQuestions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 7).ToList();
            List<ActivityQuestion> ActQuestion = new List<ActivityQuestion>();

            for (int j = 0; j < 20; j++)
            {
                ActQuestion.Add(ActivityQuestions[j]);
            }
            return View(ActQuestion);
        }

        public ActionResult ComputerActivity2()
        {
            List<ActivityQuestion> ActivityQuestions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 7).ToList();
            List<ActivityQuestion> ActQuestion = new List<ActivityQuestion>();

            for (int j = 20; j < 40; j++)
            {
                ActQuestion.Add(ActivityQuestions[j]);
            }
            return View(ActQuestion);
        }

        public ActionResult ComputerQuiz()
        {
            List<QuizQuestion> QuizQuestions = db.QuizQuestions.Where(zz => zz.QQ_ID > 60 && zz.QQ_ID < 81).ToList();
            List<QuizQuestion> QQuestion = new List<QuizQuestion>();

            for (int j = 0; j < 20; j++)
            {
                QQuestion.Add(QuizQuestions[j]);
            }
            return View(QQuestion);
        }
        public ActionResult ComputerScreen()
        {
            return View();
        }
    }
}

deliverable 2/Views/ComputerActivity/ComputerActivity.cshtml
@model IEnumerable<deliverable_2.Models.ActivityQuestion>
@{
    Layout = null;
    int counter = 1;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ComputerActivity</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body class="p-3 mb-2 bg-secondary text-dark">
</body>
<body>
    <div>
        @foreach (var item in Model)
        {
            <br />
            <h5>Question @counter</h5>
            <label>@item.Question</label>
            <br />
            <input type="radio" value="@item.option1" />@item.option1
            <br />
            <input type="radio" value="@item.option2" />@item.option2
            <br />
            <input type="radio" value="@item.option3" />@item.option3
            <br />
            <input type="radio" value="@item.ActAnswer" />@item.ActAnswer
            <br />
            counter++;
        }
        <br />
        <button type="submit" class="btn btn-success">Mark</button>
        @using (Html.BeginForm("ComputerScreen", "ComputerActivity"))
            {
            <button type="submit" class="btn-success">Cancel</button>
        }
    </div>
</body>
</html>

deliverable 2/Views/ComputerActivity/ComputerActivity2.cshtml
@model IEnumerable<deliverable_2.Models.ActivityQuestion>
@{
    Layout = null;
    int counter = 1;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ComputerActivity2</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body class="p-3 mb-2 bg-secondary text-dark">
</body>
<body>
    <div>
        @foreach (var item in Model)
        {
            <br />
            <h5>Question @counter</h5>
            <label>@item.Question</label>
            <br />
            <input type="radio" value="@item.option1" />@item.option1
            <br />
            <input type="radio" value="@item.option2" />@item.option2
            <br />
            <input type="radio" value="@item.option3" />@item.option3
            <br />
            <input type="radio" value="@item.ActAnswer" />@item.ActAnswer
            <br />
            counter++;
        }
        <br />
        <button type="submit" class="btn btn-success">Mark</button>
        @using (Html.BeginForm("ComputerScreen", "ComputerActivity"))
            {
            <button type="submit" class="btn-success">Cancel</button>
        }
    </div>
</body>
</html>

deliverable 2/Views/ComputerActivity/ComputerQuiz.cshtml
@model IEnumerable<deliverable_2.Models.QuizQuestion>
@{
    Layout = null;
    int counter = 1;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ComputerQuiz</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body class="p-3 mb-2 bg-secondary text-dark">
</body>
<body>
    <div>
        @foreach (var item in Model)
        {
            //displays question number, then quiestion
            <p>Question @counter @item.Question</p>


                  <!--storing the answer-->
            <p id="@string.Format("{0}{1}", "Ans", counter)" hidden>@item.QuizAnswer</p>
            <p id="@string.Format("{0}{1}", "Correct", counter)"></p>

            <form>
                <fieldset id="@string.Format("{0}{1}", "Form", counter)">

                    <input type="radio" name="@string.Format("{0}{1}", "Answer", counter)" value="@item.option1" id="one" />@item.option1 <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", counter)" value="@item.option2" id="two" />@item.option2 <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", counter)" value="@item.option3" id="three" />@item.option3 <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", counter)" value="@item.QuizAnswer" id="Answer" />@item.QuizAnswer <br />
                </fieldset>
            </form>
            counter++;
        }
        <p id="countt" hidden>@counter</p>


        <button class="btn-success" type="submit" name="markme" onclick="Mark()">Mark</button>

        @using (Html.BeginForm("ComputerScreen", "ComputerActivity"))
            {
            <button type="submit" class="btn-success">Cancel</button>
        }
    </div>

    <!--marking-->
    <script>

            function Mark()
            {
                //<!--the counter, after for loop the counter os saved in paragrapgh and yeah-->
                var Countt = document.getElementById("countt").innerHTML;


                var j;

                @*@// checking whether correct answer was selected*@
                for (j=1; j< Countt; j++)
                {

                    var type = "Answer" + j;
                    var Thos = document.getElementsByName(type);

                    for (var zz = 0; zz<4 ; zz++)
                    {
                        if (Thos[3].checked)
                        {
                            var time = "Correct"+j
                           document.getElementById(time).innerHTML = "Correct"
                        }
                        else
                        {
                            var time = "Correct" + j
                            document.getElementById(time).innerHTML = "Incorrect"
                        }
                    }

                    var dis = "Form" + j;
                    document.getElementById(dis).disabled = true;
                }
            }
    </script>
</body>
</html>