deliverable 2/Models/Activity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverable_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityQuestions = new HashSet<ActivityQuestion>();
        }
    
        public int Activity_ID { get; set; }
        public int Subject_ID { get; set; }
    
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityQuestion> ActivityQuestions { get; set; }
    }
}

deliverable 2/Models/Quiz.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverable_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int Quiz_ID { get; set; }
        public int Subject_ID { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}

deliverable 2/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using deliverable_2.Models;
using System.Security.Cryptography;
using System.Data.SqlClient;        //import SQL Client library

namespace deliverable_2.Controllers
{
    public class DataController : Controller
    {
        SqlConnection myConnect = new SqlConnection("Data Source=.;Initial Catalog=Education;Integrated Security=True");
        // GET: Data
       

        public ActionResult MainMenu()
        {
            return View();
        }
        public ActionResult Settings()
        {
            return View();
        }
        public ActionResult SubjectContent()
        {
            return View();
        }

        public ActionResult Diversity()
        {
            return View();
        }
        public ActionResult ActivityD()
        {
            return View();

        }
        public ActionResult ActivityR()
        {
            return View();
        }

        public ActionResult Rights()
        {
            return View();
        }


        EducationEntities db = new EducationEntities();

        //refiloe was here
        public ActionResult DiversityQuiz(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for db
            List<QuizQuestion> thisQ = db.QuizQuestions.Where(zz => zz.QQ_ID > 20 && zz.QQ_ID < 41).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass hqDetails = new refiloeclass();
                hqDetails.QID = thisQ[j].QQ_ID;
                hqDetails.Qeustion = thisQ[j].Question;
                hqDetails.Answer = thisQ[j].QuizAnswer;
                hqDetails.Option1 = thisQ[j].option1;
                hqDetails.Option2 = thisQ[j].option2;
                hqDetails.Option3 = thisQ[j].option3;

                DBStuff.Add(hqDetails);
            }

            return View(DBStuff); //sending the viewmodel to the view(this way, it will send "updated" one each time the Index view loads)
        }

        public ActionResult HRQuiz(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for the class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for the database
            List<QuizQuestion> thisQ = db.QuizQuestions.Where(zz => zz.QQ_ID > 0 && zz.QQ_ID < 21).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass details = new refiloeclass();
                details.HQID = thisQ[j].QQ_ID;
                details.HQuestion = thisQ[j].Question;
                details.HAnswer = thisQ[j].QuizAnswer;
                details.HOption1 = thisQ[j].option1;
                details.HOption2 = thisQ[j].option2;
                details.HOption3 = thisQ[j].option3;

                DBStuff.Add(details);
            }
            return View(DBStuff);
        }

        public ActionResult MHumanRights(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for the class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for the database
            List<ActivityQuestion> thisQ = db.ActivityQuestions.Where(zz => zz.AQ_ID > 0 && zz.AQ_ID < 21).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass details = new refiloeclass();
                details.RQID = thisQ[j].AQ_ID;
                details.RQuestion = thisQ[j].Question;
                details.RAnswer = thisQ[j].ActAnswer;
                details.ROption1 = thisQ[j].option1;
                details.ROption2 = thisQ[j].option2;
                details.ROption3 = thisQ[j].option3;

                DBStuff.Add(details);
            }
            return View(DBStuff);


        }
        public ActionResult MDiversityActivity(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for the class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for the database
            List<ActivityQuestion> thisQ = db.ActivityQuestions.Where(zz => zz.AQ_ID > 20 && zz.AQ_ID < 41).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass Details = new refiloeclass();
                Details.EQID = thisQ[j].AQ_ID;
                Details.EQuestion = thisQ[j].Question;
                Details.EAnswer = thisQ[j].ActAnswer;
                Details.EOption1 = thisQ[j].option1;
                Details.EOption2 = thisQ[j].option2;
                Details.EOption3 = thisQ[j].option2;

                DBStuff.Add(Details);
            }
            return View(DBStuff);
        }

        public ActionResult ADiversityActivity(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for the class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for the database
            List<ActivityQuestion> thisQ = db.ActivityQuestions.Where(zz => zz.AQ_ID > 20 && zz.AQ_ID < 41).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass Detail = new refiloeclass();
                Detail.AQID = thisQ[j].AQ_ID;
                Detail.AQuestion = thisQ[j].Question;
                Detail.AAnswer = thisQ[j].ActAnswer;
                Detail.AOption1 = thisQ[j].option1;
                Detail.AOption2 = thisQ[j].option2;
                Detail.AOption3 = thisQ[j].option3;

                DBStuff.Add(Detail);
            }
            return View(DBStuff);
        }
        public ActionResult AHumanRights(string Question, string Answer, string option1, string option2, string option3)
        {
            //list for the class
            List<refiloeclass> DBStuff = new List<refiloeclass>();
            //list for the database
            List<ActivityQuestion> thisQ = db.ActivityQuestions.Where(zz => zz.AQ_ID > 40 && zz.AQ_ID < 61).ToList();

            for (int j = 0; j < 10; j++)
            {
                refiloeclass details = new refiloeclass();
                details.LQID = thisQ[j].AQ_ID;
                details.LQuestion = thisQ[j].Question;
                details.LAnswer = thisQ[j].ActAnswer;
                details.LOption1 = thisQ[j].option1;
                details.LOption1 = thisQ[j].option2;
                details.LOption3 = thisQ[j].option3;

                DBStuff.Add(details);
            }
            return View(DBStuff);
        }

        public ActionResult Mathactivity()
        {
            return View();
        }
        public ActionResult Financeactivity()
        {
            return View();
        }

        public ActionResult Math()
        {
            return View();
        }

        public ActionResult Quiz()
        {
            return View();
        }

        public ActionResult Activity()
        {
            return View();
        }

        public ActionResult Finances()
        {
            return View();
        }

        public ActionResult EmailEtiquette()
        {
            return View();
        }

        public ActionResult ComputerSkills()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

deliverable 2/Controllers/FinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using deliverable_2.Models;

namespace deliverable_2.Controllers
{
    public class FinanceController : Controller
    {
        // GET: Finance
        EducationEntities db = new EducationEntities();
        public ActionResult FiananceActivityone()
        {
            List<ActivityQuestion> Questions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 3).ToList();

            List<ActivityQuestion> thisQ = new List<ActivityQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(0, 20);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
        public ActionResult FiananceActivitytwo()
        {
            List<ActivityQuestion> Questions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 2).ToList();

            List<ActivityQuestion> thisQ = new List<ActivityQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(19, 39);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
        public ActionResult FianaceQuize()
        {

            List<QuizQuestion> Questions = db.QuizQuestions.Where(zz => zz.QQ_ID > 100).ToList();

            List<QuizQuestion> thisQ = new List<QuizQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(0, 20);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
    }
}

deliverable 2/Views/Data/ADiversityActivity.cshtml
@model List<deliverable_2.Controllers.refiloeclass>
@{
    Layout = null;
    //to number the questions accordlignnly
    int count = 1;
    //keeps track of correct answer count
    int AnswerCount = 0;
}

<!DOCTYPE html>

<html>
<head>
    <title>Diversity Activity </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body class="bg-danger text-black">

    <div>
        <h1>Diversity Activity One</h1>
        <p>Please note that the following will now contribute towards your progress mark</p>
        @foreach (var items in Model)
        {
            <h5>Question @count @items.AQuestion</h5>

               <!--storing the answer-->
            <p id="@string.Format("{0}{1}", "Ans", count)" hidden>@items.AAnswer</p>
            <p id="@string.Format("{0}{1}", "Correct", count)"></p>

            <form>

                <fieldset id="@string.Format("{0}{1}", "Form", count)">

                    <input type="radio" name="@string.Format("{0}{1}", "Answer", count)" />@items.AAnswer <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", count)" />@items.AOption1 <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", count)" />@items.AOption2 <br />
                    <input type="radio" name="@string.Format("{0}{1}", "Answer", count)" />@items.AOption3 <br />

                </fieldset>
            </form>
            count++;
        }
        <p id="countt" hidden>@count</p>

        <button class="btn-success" type="submit" name="markme" onclick="Mark()">Mark</button>
        @using (Html.BeginForm("ActivityD", "Data"))
        {
            <button class="btn-success">Cancel</button>
        }
    </div>

    <!--marking-->
    <script>

            function Mark()
            {
                @*@//the counter, after for loop the counter os saved in paragrapgh and yeah*@

                var Countt = document.getElementById("countt").innerHTML;


                var j;

                @*@// checking whether correct answer was selected*@

                for (j=1; j< Countt; j++)
                {

                    var type = "Answer" + j;
                    var Thos = document.getElementsByName(type);

                    for (var zz = 0; zz<4 ; zz++)
                    {
                        if (Thos[3].checked)
                        {
                            var time = "Correct"+j
                           document.getElementById(time).innerHTML = "Correct"
                        }
                        else
                        {
                            var time = "Correct" + j
                            document.getElementById(time).innerHTML = "Incorrect"
                        }
                    }

                    var dis = "Form" + j;
                    document.getElementById(dis).disabled = true;
                }
            }

    </script>
</body>
</html>

deliverable 2/Views/Data/ActivityR.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ActivityR</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body style="background-color:lightblue">
</body>
<body style="text-align:center" class="bg-danger text-black">
    <h1>Human Rights Activities</h1>

    <div class="flex-container" style="text-align:center;float:right">
        <div class="row">
            <div class="col-*4* flex-item" style="width:400px">
                <img class="card-img-top" style="width:250px; height:200px" src="https://cdn1.msw.usc.edu/content/0f530cd191e14565afa199d6957ca754/200_Guide_DiversityWorkshop_act1.jpg" alt="act1.jpg" />
                <div class="card-body">
                    <h4 class="card-title" style="font-size:16px">Activity One</h4>
                    @using (Html.BeginForm("AHumanRights", "Data"))
                    {
                        <button type="submit" class="btn btn-primary btn-lg">Activity one</button>
                    }

                </div>
            </div>
        </div>

    </div>


    <div class="flex-container" style="text-align:center;float:left;">
        <div class="row">
            <div class="col-*4* flex-item" style="width:400px">
                <img class="card-img-top" style="width:250px; height:200px" src="https://cdn3.msw.usc.edu/content/494ebc2a088a46deafad646ae14aaf80/200_Guide_DiversityWorkshop_act2.jpg" alt="act2.jpg" />
                <div class="card-body">
                    <h4 class="card-title" style="font-size:16px">Activity Two</h4>
                    @using (Html.BeginForm("AHumanRights", "Data"))
                    {
                        <button type="submit" class="btn btn-primary btn-lg">Activity two</button>
                    }


                </div>
            </div>
        </div>

    </div>
    <div>
    </div>
</body>
</html>

deliverable 2/Views/Data/Diversity.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Diversity</title>
    <meta charset="utf-8">
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


</head>
<body>
    <div class="parent-div" style="width:100%">
    @using (Html.BeginForm("MainMenu", "Data"))
            {  <div class="first_btn">
        <button type="submit" class="btn btn-default">Main menu</button>
    </div>
    }

    @using (Html.BeginForm("DiversityQuiz", "Data"))
            {
        <div class="second_btn">
            <button type="submit" class="btn btn-default">Quiz</button>
        </div>
    }

    @using (Html.BeginForm("ActivityD", "Data"))
            {  <div class="third_btn">
        <button type="submit" class="btn btn-default">Return to Activity view</button>
    </div>
    }
    @using (Html.BeginForm("SubjectContent", "Data"))
            {
        <button type="submit" class="btn btn-default">Subject Content</button>
    }
        </div>
    <div class="bg-danger text-black">
        <h1 align="center">Diversity</h1>
        <p>
            We live in an era filled with unique people who practice different religions, cultures and ways of life.
            Understanding other peoples ways can be helpful and it allows for better interactions. Diversity means
            understanding that each individual is unique, and recognising individual differences.
        </p>

        <h3>Content Objectives:</h3>

        <ol style="list-style-type:circle">
            <li>Have clear understanding of what diversity is</li>
            <li>Know the important of diversity</li>
            <li>Be able to give examples of diversity</li>
            <li>Be able to advise a person in a situation where there are diversity issues</li>
        </ol>
        <br />
        <p>
            Diversity can be simply defined as the state of being diverse. Now, this is an extremely vague meaning and many people don't know when it applies.
            Diversity comes in many forms, namely, religion, race, gender, sexual orientation, culture, socioeconomic backgrounds and pretty much anything that
            makes one person different from the next. All these factors contribute to a persons unique experience.
            <br />
            We are entering the Fourth Industrial Evolution(4IR), which can be defined as the second wave of the internet. What this means is that there will
            be an increase in the number of digital connections between people, as well as in between people and things. So basically, computers are taking over
            people's jobs because of this automation. It is crucial for the youth and people in general to have some sort of computer skills so that they don't lose
            their jobs.
        </p>
        <ol style="list-style-type:circle">
            Diversity is important in the 21st Century because of 5 main reasons.
            <li>Productivity</li>
            <li>Becoming a World Citizen</li>
            <li>Perspective</li>
            <li>Growing Acceptance, Diminishing Discrimination</li>
            <li>Richer Life Experience</li>
        </ol>
        <p>
            In terms of productivity, everyone has their own way of viewing problems. This is shaped by the individual experiences that they have had.
            When tackling any problem, it would make sense to have as many different perspectives and options as possible. It is better than having the
            same opinion and thoughts from everyone. When you experience diversity in your everyday life, you will frequently be exposed to many different cultures, traditions and practices which are not
            like yours. You will enteract with different people from  other communities and be constantly learning. This will improve your social development and improve
            your understandingof the world. This will prepare you for being a part of the global society.
            <br />
            Listening to other people and hearing their experience can change your perspective on thoughts and the way in which you do things. When listening to
            others and hearing their priorities, struggles and values you get a clearer idea of where they are coming from. This will help you appreciate one another's motivation
            and hardships. We are currently living in a time where people are hypersensitive. This means that people's immune systems are proned to produce undesirable reactions. One must be extremely
            sensitive when dealing and interacting with human beings. Over the past few years, there has been an increase in acceptance. Accepting people goes beyond tolerating them. It is about
            communicating with these people and realising that you have some thing in common. On the other hand discrimination and being treating people differently because of who they are is
            diminishing. Those who engage in such behaviour are often scrutinized by society of the people around them.
            <br />
            Richer life experience is aboutnew ideas, views, practices to stimulate and inspire us. Diversity is colourful. Being around people who are exatly like you and think just like you
            all the time would be a dreadful experience. This helps you learn about others and will ultimately result in you growing you acceptance. All forms of hate speech should be frowned upon.
        </p>
      



    </div>
</body>
</html>

deliverable 2/Views/Data/Financeactivity.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SubjectContent</title>
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body style="background-color: lightblue;text-align:center">
    <h1 style="text-align:center">Finance activities</h1>
    <h2>Please select a button</h2>

    <div class="parent-div" style="width:100%">
        @using (Html.BeginForm("MainMenu", "Data"))
        {  <div class="first_btn">
            <button type="submit" class="btn btn-default">Main menu</button>
        </div>
        }

        @using (Html.BeginForm("SubjectContent", "Data"))
        {
            <div class="second_btn">
                <button type="submit" class="btn btn-default">Subject content</button>
            </div>
        }

        @using (Html.BeginForm("Financeactivity", "Data"))
        {  <div class="third_btn">
            <button type="submit" class="btn btn-default">Activity view</button>
        </div>
        }
    </div>
    @using (Html.BeginForm("FiananceActivityone", "Finance"))
    {
        <div class="flex-container" style="text-align:center">
            <div class="row">
                <div class="col-*4* flex-item" style="width:400px;float:left">
                    <img class="card-img-top" style="width:250px;height:200px" src="https://cdn1.msw.usc.edu/content/0f530cd191e14565afa199d6957ca754/200_Guide_DiversityWorkshop_act1.jpg" alt="Activity one">
                    <div class="card-body">
                        <h4 class="card-title" style="font-size:16px">Activity One</h4>


                        <button type="submit" class="btn btn-primary btn-lg">Activity one</button>
                    </div>
                </div>
            </div>
        </div>


    }
    @using (Html.BeginForm("FiananceActivitytwo", "Finance"))
            {
        <div class="flex-container">
            <div class="row">
                <div class="col-*4* flex-item" style="width:400px;float:left">
                    <img class="card-img-top" style="width:250px;height:200px" src="https://cdn3.msw.usc.edu/content/494ebc2a088a46deafad646ae14aaf80/200_Guide_DiversityWorkshop_act2.jpg" alt="Activity two">
                    <div class="card-body">
                        <h4 class="card-title" style="font-size:16px">Activity Two</h4>


                        <button type="submit" class="btn btn-primary btn-lg">Activity two</button>
                    </div>
                </div>
            </div>
        </div>
    }





</body>

</html>

deliverable 2/Views/Data/Finances.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SubjectContent</title>
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body style="background-color:aquamarine">

    <div class="parent-div" style="width:100%">
        @using (Html.BeginForm("MainMenu", "Data"))
            {  <div class="first_btn">
            <button type="submit" class="btn btn-default">Main menu</button>
        </div>
        }

        @using (Html.BeginForm("Quiz", "Data"))
            {
            <div class="second_btn">
                <button type="submit" class="btn btn-default">Quiz</button>
            </div>
        }

        @using (Html.BeginForm("Activity", "Data"))
            {  <div class="third_btn">
            <button type="submit" class="btn btn-default">Return to Activity view</button>
        </div>
        }
    </div>

    <div class="DIV">
        <h1>Finances</h1>
        <p>
            Finance is a field that analysers the assets, liability and owners’ equity. The most common question that most
            people ask is what is assets, liability and owners’ equity, asset is any resource owned by the business where as liability
            is what the company owes to either another company or person and owners’ equity or equity is the difference between the value
            of the assets and the value of the liabilities of something owed. In this section we will be dealing with the basic accounting
            rules and statements. The content below will help you better understand the accounting principles and how to draft up a personal budget a
            nd how to calculate in the budget.
        </p>
        <br />
        <h2>Debtor </h2>
        <p>
            You will hear these words all around you not only when talking to finance people but in general. What is a debtor, a debtor is someone that buys something from
            your business these could be products that your company sells or services that you provide. Do not confuse debtors with capital, capital is the starting money to have to start your business/company. Whereas a debtor is one who purchases a product from your business, a debtor is classified as an asset.
        </p>
        <br />
        <h2>Creditors</h2>
        <p>
            A  creditor is classified as a liability and a creditor is someone who you as the company owes money to. This will have a negative impact on the company because the
            company now loses money because you will have to pay all liabilities in the business.
        </p>
        <br />
        <h2>Income</h2>
        <p>
            Income in anything that brings money into the business this can be money that you have received from investments or money that was made from sales. Therefore, anything that brings money into the business is classified as an income. These services rendered and sales are all income. Please take note income
            is part of Equity and not assets most people struggle with understanding this concept
        </p>
        <br />
        <h2>Expenses </h2>
        <p>
            Expenses are easy to understand these are all things that the company buys for the company and anything that needs to be paid however, this is not classified as a liability because a liabilities of something owed that needs to be paid off where as an expense is more of a purchase. Things such as advertising is an expense, salaries/wagers and if it’s a personal
            budget you compiling expenses will include going out money and buying food, clothes and thing that you purchase.
        </p>
        <br />
        <h2>Personal budget</h2>
        <p>
            When dealing with a personal budget you first need to understand what a personal budget is, a personal budget or home budget is a finance plan that allocates future personal income towards expenses, savings and debt repayment. Past spending and personal debt are considered when creating a personal budget. The basic format is that you first start with Income as your heading then you list all your incomes, these will include your wage or pocket money. You then total up all income. You then create your expenses heading and list all possible expenses you might have through the month, after you calculate the total amount of expenses. Finally, you subtract the expenses total from the income total and that amount is how much money you will have left. However, if you have a negative amount this means that you
            have more expenses that income and need to wither find a way to make more income or you need to reduce your expenses.
        </p>


    </div>

</body>
</html>