deliverable 2/Controllers/MathPractiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using deliverable_2.Models;

namespace deliverable_2.Controllers
{
    public class MathPractiseController : Controller
    {
        EducationEntities db = new EducationEntities();
        public ActionResult ActivityOne()
        {
            List<ActivityQuestion> Questions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 2).ToList();

            List<ActivityQuestion> thisQ = new List<ActivityQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(0, 20);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
        public ActionResult Activitytwo()
        {
            List<ActivityQuestion> Questions = db.ActivityQuestions.Where(zz => zz.Activity_ID == 2).ToList();

            List<ActivityQuestion> thisQ = new List<ActivityQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(19, 39);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
        public ActionResult MathQuize()
        {
            List<QuizQuestion> Questions = db.QuizQuestions.Where(zz => zz.QQ_ID > 80 && zz.QQ_ID < 101).ToList();

            List<QuizQuestion> thisQ = new List<QuizQuestion>();
            List<int> listNumbers = new List<int>();
            int v;
            Random rand = new Random();
            for (int j = 0; j < 10; j++)
            {
                do
                {
                    v = rand.Next(0, 20);
                } while (listNumbers.Contains(v));
                listNumbers.Add(v);
                thisQ.Add(Questions[v]);
            }


            return View(thisQ.ToList());
        }
    }
}

deliverable 2/Views/MathPractise/ActivityOne.cshtml
@model IEnumerable<deliverable_2.Models.ActivityQuestion>

@{
    Layout = null;
    int counter = 1;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ActivityOne</title>
    <meta charset="utf-8">
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/Calculator.js"></script>
    <style>
        body {
            position: relative;
        }
    </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">


    <br />
    <br />
    <br />
    <body class="bg-info text-black">
        <h1>Instructions</h1>
        <p>BEFORE starting test please click on the calculator button below,the calculator is located at the end of the questions because you dont need it when answering the questions,however it is there incase.Then read through all questions and answer to best ability. You will have to complete the activity in one sit in, you can not exit the activity and come back to complete it. If you do you will lose those answers </p><br />
        <h2>Note</h2><p>Please round answers to 3 decimal places if nesseccary.Once you have answered all questions you can click the submit button you can no longer change your answeres, they will be Marked. If you click the Cancel button alll your answers will be lost and you will have to retake the activity.</p>
        <br />
        <div style="text-align:center">
            <button onclick="calculator()" id="btn1" class="bg-dark text-white">Calculator</button>
        </div>

    </body>


    @foreach (var item in Model)
    {
        <form id="@string.Format("{0}{1}", "Form", counter)" disabled>
            <div id="question1" class="bg-info text-black" style="padding-top:70px;padding-bottom:70px;background-color:dodgerblue">
                <h1>Question @counter</h1>
                <br />

                <label>@item.Question</label>
                <p id="@string.Format("{0}{1}", "Ans", counter)" hidden>@item.ActAnswer</p>

                <br />
                <br>
                <input type="number" step=".03" id="@string.Format("{0}{1}", "Typed", counter)" />
                <p style="text-decoration-color:green" id="@string.Format("{0}{1}", "Correct", counter)"></p>
                <p style="text-decoration-color:red" id="@string.Format("{0}{1}", "Incorrect", counter)"></p>
            </div>
        </form>
        counter++;

    }
    <h2 style="text-align:center">Calculator</h2>



    <div class="calculator,bg-info text-black" style="text-align:center">

        <input type="text" class="calculator-screen" value="" disabled />

        <div class="calculator-keys, bg-info text-black" style="text-align:center">

            <button type="button" class="operator" value="+">+</button>
            <button type="button" class="operator" value="-">-</button>
            <button type="button" class="operator" value="*">&times;</button>
            <button type="button" class="operator" value="/">&divide;</button>

            <button type="button" value="7">7</button>
            <button type="button" value="8">8</button>
            <button type="button" value="9">9</button>


            <button type="button" value="4">4</button>
            <button type="button" value="5">5</button>
            <button type="button" value="6">6</button>


            <button type="button" value="1">1</button>
            <button type="button" value="2">2</button>
            <button type="button" value="3">3</button>


            <button type="button" value="0">0</button>
            <button type="button" class="decimal" value=".">.</button>
            <button type="button" class="all-clear" value="all-clear">AC</button>

            <button type="button" class="equal-sign operator" value="=">=</button>

        </div>

    </div>
    <br />
    <div style="text-align:center">
        <p id="Counter" hidden>@counter</p>
        <div class="parent-div">
            <div class="first_btn">
                <button onclick="Mark()" class="btn btn-success" id="mark">Mark</button>
            </div>


            <button class="btn btn-success" id="Submit" hidden>Submit</button>


            @using (Html.BeginForm("Mathactivity", "Data"))
            {
                <div class="second_btn">
                    <button type="submit" class="btn btn-success">Return to Activity view </button>
                </div>


            }
            @using (Html.BeginForm("Activitytwo", "MathPractise"))
            {
                <div class="third_btn">
                    <button type="submit" class="btn btn-success">Activity Two</button>
                </div>

            }
        </div>





    </div>

    <script>



            function Mark() {

                var Countt = document.getElementById("Counter").innerHTML;




                var j;

                for (j = 1; j < Countt; j++) {

                    var Ans = "Ans" + j;
                    var Answer = document.getElementById(Ans).innerHTML;

                    var type = "Typed" + j;
                    var Typed = document.getElementById(type).value;

                    if (Answer == Typed)
                    {
                        var name = "Correct" + j;
                        document.getElementById(name).innerHTML = "Correct";
                        document.getElementById(type).disabled = true;


                    }
                    else
                    {
                        var name = "Incorrect" + j;
                        document.getElementById(name).innerHTML = "Incorrect";
                        document.getElementById(type).disabled = true;
                    }
                }
                document.getElementById("mark").style.display = "block";
                document.getElementById("Submit").style.display = "none";
            }
    </script>
</body>

</html>

deliverable 2/Views/MathPractise/Activitytwo.cshtml
@model IEnumerable<deliverable_2.Models.ActivityQuestion>

@{
    Layout = null;
    int counter = 1;
    int Mark = 0;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ActivityTwo</title>
    <meta charset="utf-8">
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/Calculator.js"></script>
    <script src="~/Calculator.js"></script>
    <style>
        body {
            position: relative;
        }
    </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">


    <br />
    <br />
    <br />
    <body class="bg-info text-black">
        <h1>Instructions</h1>
        <p>BEFORE starting test please click on the calculator button below,the calculator is located at the end of the questions because you dont need it when answering the questions,however it is there incase.Then read through all questions and answer to best ability. You will have to complete the activity in one sit in, you can not exit the activity and come back to complete it. If you do you will lose those answers </p><br />
        <h2>Note</h2><p>Please round answers to 3 decimal places if nesseccary.Once you have answered all questions you can click the submit button you can no longer change your answeres, they will be Marked. If you click the Cancel button alll your answers will be lost and you will have to retake the activity.</p>
        <br />
        <div style="text-align:center">

        </div>
        <button onclick="calculator()" id="btn1" class="bg-dark text-white">Calculator</button>
    </body>


    @foreach (var item in Model)
    {
        <form id="@string.Format("{0}{1}", "Form", counter)" disabled>
            <div id="question1" class="bg-info text-black" style="padding-top:70px;padding-bottom:70px;background-color:dodgerblue">
                <h1>Question @counter</h1>
                <br />

                <label>@item.Question</label>
                <p id="@string.Format("{0}{1}", "Ans", counter)" hidden>@item.ActAnswer</p>

                <br />
                <br>
                <input type="number" step=".03" id="@string.Format("{0}{1}", "Typed", counter)" />
                <p style="text-decoration-color:green" id="@string.Format("{0}{1}", "Correct", counter)"></p>
                <p style="text-decoration-color:red" id="@string.Format("{0}{1}", "Incorrect", counter)"></p>
            </div>
        </form>
        counter++;

    }
    <h2 style="text-align:center">Calculator</h2>



    <div class="calculator,bg-info text-black" style="text-align:center">

        <input type="text" class="calculator-screen" value="" disabled />

        <div class="calculator-keys, bg-info text-black" style="text-align:center">

            <button type="button" class="operator" value="+">+</button>
            <button type="button" class="operator" value="-">-</button>
            <button type="button" class="operator" value="*">&times;</button>
            <button type="button" class="operator" value="/">&divide;</button>

            <button type="button" value="7">7</button>
            <button type="button" value="8">8</button>
            <button type="button" value="9">9</button>


            <button type="button" value="4">4</button>
            <button type="button" value="5">5</button>
            <button type="button" value="6">6</button>


            <button type="button" value="1">1</button>
            <button type="button" value="2">2</button>
            <button type="button" value="3">3</button>


            <button type="button" value="0">0</button>
            <button type="button" class="decimal" value=".">.</button>
            <button type="button" class="all-clear" value="all-clear">AC</button>

            <button type="button" class="equal-sign operator" value="=">=</button>

        </div>

    </div>
    <br />
    <div style="text-align:center">
        <p id="Counter" hidden>@counter</p>
        <div class="parent-div">
            <div class="first_btn">
                <button onclick="Mark()" class="btn btn-success" id="mark">Mark</button>
            </div>

            <button class="btn btn-success" id="Submit" hidden>Submit</button>


            @using (Html.BeginForm("Mathactivity", "Data"))
            {
                <div class="second_btn">
                    <button type="submit" class="btn btn-success">Return to Activity view</button>
                </div>



            }
            @using (Html.BeginForm("MathQuiz", "MathPractise"))
            {
                <div class="third_btn">
                    <button type="submit" class="btn btn-success">Activity Two</button>
                </div>

            }
        </div>

    </div>


</body>

</html>

deliverable 2/Views/MathPractise/MathQuize.cshtml
@model IEnumerable<deliverable_2.Models.QuizQuestion>

@{
    Layout = null;
    int counter = 1;
    

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Quiz</title>
    <meta charset="utf-8">
    <script src="~/Calculator.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/Calculator.js"></script>
    <style>
        body {
            position: relative;
        }
    </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">


    <body class="bg-info text-black">
        <h1>Instructions</h1>
        <p>BEFORE starting test please click on the calculator button below,the calculator is located at the end of the questions because you dont need it when answering the questions,however it is there incase.Then read through all questions and answer to best ability. You will have to complete the activity in one sit in, you can not exit the activity and come back to complete it. If you do you will lose those answers </p><br />
        <h2>Note</h2><p>Please round answers to 3 decimal places if nesseccary.Once you have answered all questions you can click the submit button you can no longer change your answeres, they will be Marked. If you click the Cancel button alll your answers will be lost and you will have to retake the activity.</p>
        <br />
        <div style="text-align:center">
            <button onclick="calculator()" id="btn1" class="bg-dark text-white">Calculator</button>
        </div>

    </body>



    @foreach (var item in Model)
    {
        <form id="@string.Format("{0}{1}", "Form", counter)" disabled>
            <div id="question1" class="bg-info text-black" style="padding-top:70px;padding-bottom:70px;background-color:dodgerblue">
                <h1>Question @counter</h1>
                <br />
                <label>@item.Question</label>
                <p id="@string.Format("{0}{1}", "Ans", counter)" hidden>@item.QuizAnswer</p>
                <p id="@string.Format("{0}{1}", "MAR", counter)" hidden>@item.Mark</p>
                <br />
                <br>
                <input type="number" step=".03" id="@string.Format("{0}{1}", "Typed", counter)" />
                <p style="text-decoration-color:green" id="@string.Format("{0}{1}", "Correct", counter)"></p>
                <p style="text-decoration-color:red" id="@string.Format("{0}{1}", "Incorrect", counter)"></p>
            </div>
        </form>
        counter++;

    }
    <h2 style="text-align:center">Calculator</h2>
    <div class="calculator,bg-info text-black" style="text-align:center">
        <input type="text" style="text-align:center" class="calculator-screen" value="" disabled />
        <div class="calculator-keys, bg-info text-black" style="text-align:center">
            <button type="button" class="operator" value="+">+</button>
            <button type="button" class="operator" value="-">-</button>
            <button type="button" class="operator" value="*">&times;</button>
            <button type="button" class="operator" value="/">&divide;</button>
            <button type="button" value="7">7</button>
            <button type="button" value="8">8</button>
            <button type="button" value="9">9</button>

            <button type="button" value="4">4</button>
            <button type="button" value="5">5</button>
            <button type="button" value="6">6</button>

            <button type="button" value="1">1</button>
            <button type="button" value="2">2</button>
            <button type="button" value="3">3</button>

            <button type="button" value="0">0</button>
            <button type="button" class="decimal" value=".">.</button>
            <button type="button" class="all-clear" value="all-clear">AC</button>
            <button type="button" class="equal-sign operator" value="=">=</button>
        </div>
    </div>

    <div style="text-align:center">
        <p id="Counter" hidden>@counter</p>
        <div class="parent-div">
            <div class="first_btn">
                <button onclick="Mark()" class="btn btn-success" id="mark">Mark</button>
            </div>
            <button class="btn btn-success" id="Submit" hidden>Submit</button>

            @using (Html.BeginForm("Mathactivity", "Data"))
            {
                <div class="second_btn">
                    <button type="submit" class="btn btn-success">Return to Activity view</button>
                </div>



            }
            @using (Html.BeginForm("MathQuiz", "MathPractise"))
            {
                <div class="third_btn">
                    <button type="submit" class="btn btn-success">Activity Two</button>
                </div>

            }
        </div>
    </div>

    <script>



            function Mark() {

                var Countt = document.getElementById("Counter").innerHTML;
                var Marks = 0;
                var Total = 0;



                var j;

                for (j = 1; j < Countt; j++) {

                    var Ans = "Ans" + j;
                    var Answer = document.getElementById(Ans).innerHTML;

                    var type = "Typed" + j;
                    var Typed = document.getElementById(type).value;

                    var markAll = "MAR" + j;
                    var thisMark = document.getElementById(markAll).innerHTML;
                    Total += thisMark;
                    

                    if (Answer == Typed)
                    {
                        var name = "Correct" + j;
                        
                        
                        document.getElementById(name).innerHTML = "Correct";
                        document.getElementById(type).disabled = true;
                        

                        Marks = Marks + thisMark;



                    }
                    else
                    {
                        var name = "Incorrect" + j;
                        document.getElementById(name).innerHTML = "Incorrect";
                        document.getElementById(type).disabled = true;
                    }
                    
                }
                document.getElementById("id").disabled = true;
                alert("Total equals to " + Marks + "/" + Total);

            }
    </script>
</body>
</html>